Traceback (most recent call last):
  File "/home/mudit/bot-battle/.venv/lib/python3.10/site-packages/pydantic/type_adapter.py", line 277, in _init_core_attrs
    self._core_schema = _getattr_no_parents(self._type, '__pydantic_core_schema__')
  File "/home/mudit/bot-battle/.venv/lib/python3.10/site-packages/pydantic/type_adapter.py", line 119, in _getattr_no_parents
    raise AttributeError(attribute)
AttributeError: __pydantic_core_schema__

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mudit/bot-battle/submission1/submission.py", line 393, in <module>
    main()
  File "/home/mudit/bot-battle/submission1/submission.py", line 46, in main
    query = game.get_next_query()
  File "/home/mudit/bot-battle/risk-helper/src/risk_helper/game.py", line 36, in get_next_query
    query = self.connection.get_next_query()
  File "/home/mudit/bot-battle/risk-helper/src/risk_helper/connection.py", line 48, in get_next_query
    return TypeAdapter(QueryType).validate_json(self._receive())
  File "/home/mudit/bot-battle/.venv/lib/python3.10/site-packages/pydantic/type_adapter.py", line 264, in __init__
    self._init_core_attrs(rebuild_mocks=False)
  File "/home/mudit/bot-battle/.venv/lib/python3.10/site-packages/pydantic/type_adapter.py", line 142, in wrapped
    return func(self, *args, **kwargs)
  File "/home/mudit/bot-battle/.venv/lib/python3.10/site-packages/pydantic/type_adapter.py", line 284, in _init_core_attrs
    self._core_schema = _get_schema(self._type, config_wrapper, parent_depth=self._parent_depth)
  File "/home/mudit/bot-battle/.venv/lib/python3.10/site-packages/pydantic/type_adapter.py", line 103, in _get_schema
    schema = gen.clean_schema(schema)
  File "/home/mudit/bot-battle/.venv/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 448, in clean_schema
    schema = simplify_schema_references(schema)
  File "/home/mudit/bot-battle/.venv/lib/python3.10/site-packages/pydantic/_internal/_core_utils.py", line 443, in simplify_schema_references
    schema = walk_core_schema(schema, collect_refs)
  File "/home/mudit/bot-battle/.venv/lib/python3.10/site-packages/pydantic/_internal/_core_utils.py", line 414, in walk_core_schema
    return f(schema.copy(), _dispatch)
  File "/home/mudit/bot-battle/.venv/lib/python3.10/site-packages/pydantic/_internal/_core_utils.py", line 430, in collect_refs
    recurse(definition, collect_refs)
  File "/home/mudit/bot-battle/.venv/lib/python3.10/site-packages/pydantic/_internal/_core_utils.py", line 197, in walk
    return f(schema, self._walk)
  File "/home/mudit/bot-battle/.venv/lib/python3.10/site-packages/pydantic/_internal/_core_utils.py", line 435, in collect_refs
    new = recurse(s, collect_refs)
  File "/home/mudit/bot-battle/.venv/lib/python3.10/site-packages/pydantic/_internal/_core_utils.py", line 200, in _walk
    schema = self._schema_type_to_method[schema['type']](schema.copy(), f)
  File "/home/mudit/bot-battle/.venv/lib/python3.10/site-packages/pydantic/_internal/_core_utils.py", line 209, in _handle_other_schemas
    schema['schema'] = self.walk(sub_schema, f)  # type: ignore
  File "/home/mudit/bot-battle/.venv/lib/python3.10/site-packages/pydantic/_internal/_core_utils.py", line 197, in walk
    return f(schema, self._walk)
  File "/home/mudit/bot-battle/.venv/lib/python3.10/site-packages/pydantic/_internal/_core_utils.py", line 441, in collect_refs
    return recurse(s, collect_refs)
  File "/home/mudit/bot-battle/.venv/lib/python3.10/site-packages/pydantic/_internal/_core_utils.py", line 200, in _walk
    schema = self._schema_type_to_method[schema['type']](schema.copy(), f)
  File "/home/mudit/bot-battle/.venv/lib/python3.10/site-packages/pydantic/_internal/_core_utils.py", line 337, in handle_model_fields_schema
    replaced_field['schema'] = self.walk(v['schema'], f)
  File "/home/mudit/bot-battle/.venv/lib/python3.10/site-packages/pydantic/_internal/_core_utils.py", line 197, in walk
    return f(schema, self._walk)
  File "/home/mudit/bot-battle/.venv/lib/python3.10/site-packages/pydantic/_internal/_core_utils.py", line 441, in collect_refs
    return recurse(s, collect_refs)
  File "/home/mudit/bot-battle/.venv/lib/python3.10/site-packages/pydantic/_internal/_core_utils.py", line 200, in _walk
    schema = self._schema_type_to_method[schema['type']](schema.copy(), f)
  File "/home/mudit/bot-battle/.venv/lib/python3.10/site-packages/pydantic/_internal/_core_utils.py", line 283, in handle_dict_schema
    schema['values_schema'] = self.walk(values_schema, f)
  File "/home/mudit/bot-battle/.venv/lib/python3.10/site-packages/pydantic/_internal/_core_utils.py", line 197, in walk
    return f(schema, self._walk)
  File "/home/mudit/bot-battle/.venv/lib/python3.10/site-packages/pydantic/_internal/_core_utils.py", line 441, in collect_refs
    return recurse(s, collect_refs)
  File "/home/mudit/bot-battle/.venv/lib/python3.10/site-packages/pydantic/_internal/_core_utils.py", line 200, in _walk
    schema = self._schema_type_to_method[schema['type']](schema.copy(), f)
  File "/home/mudit/bot-battle/.venv/lib/python3.10/site-packages/pydantic/_internal/_core_utils.py", line 298, in handle_union_schema
    new_choices.append(self.walk(v, f))
  File "/home/mudit/bot-battle/.venv/lib/python3.10/site-packages/pydantic/_internal/_core_utils.py", line 197, in walk
    return f(schema, self._walk)
  File "/home/mudit/bot-battle/.venv/lib/python3.10/site-packages/pydantic/_internal/_core_utils.py", line 439, in collect_refs
    return core_schema.definition_reference_schema(schema_ref=ref)
  File "/home/mudit/bot-battle/.venv/lib/python3.10/site-packages/pydantic_core/core_schema.py", line 3712, in definition_reference_schema
    def definition_reference_schema(
KeyboardInterrupt
